version: '3'
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: nest-template
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: notsecret
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - ./new-database:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - backend

volumes:
  new-database: {}

networks:
    backend:
        driver: bridge